# Use alt-vim keys without prefix to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D 
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# No delay for ESC key press
set -sg escape-time 0

# Enable mouse behavior
setw -g mouse on

set -g default-terminal "screen-256color"
